# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 20:35:46 2020

@author: ISAAC
"""
empresa='SIMAN'

columns= ['Fecha',
          'Empresa',
          'Departamento',
          'Categoria',
          'SubCategoria',
          'id',
          'Sku',
          'Nombre',
          'Descripcion',
          'Marca',
          'ListaPreciosMax',
          'ListaPreciosMin',
          'PrecioVentaMax',
          'PrecioVentaMin',
          'Modelo',
          'Genero']

# var links = document.querySelectorAll('.vtex-menu-2-x-submenuWrapper a')
# for(var i = 0; i< links.length; i++){
#     console.log('\''+links[i].href+'\',')
# }
siman_moda=[
'https://sv.siman.com/blusas/damas/moda/ropa?map=sub-categoria,sexo,departmento,categoria',
'https://sv.siman.com/camisetas/damas/moda/ropa?map=sub-categoria,sexo,departmento,categoria',
'https://sv.siman.com/damas/moda/pantalones/ropa?map=sexo,departmento,sub-categoria,categoria',
'https://sv.siman.com/damas/jeans/moda/ropa?map=sexo,sub-categoria,departmento,categoria',
'https://sv.siman.com/damas/moda/ropa/vestidos?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/damas/faldas/moda/ropa?map=sexo,sub-categoria,departmento,categoria',
'https://sv.siman.com/abrigos/damas/moda/ropa?map=sub-categoria,sexo,departmento,categoria',
'https://sv.siman.com/blazer/damas/moda/ropa?map=sub-categoria,sexo,departmento,categoria',
'https://sv.siman.com/damas/moda/ropa/trajes-de-bano?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/moda/ropa?fuzzy=0&map=departmento,marca,categoria&operator=and&page=1&query=/moda/rbx/ropa',
'https://sv.siman.com/damas/moda/ropa/maternidad?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/damas/moda/ropa/ropa-interior?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/damas/moda/ropa/ropa-de-dormir?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/calzado/moda?fuzzy=0&map=categoria,sexo,departmento&operator=and&query=/calzado/damas/moda',
'https://sv.siman.com/accesorios/carteras/moda?map=categoria,sub-categoria,departmento',
'https://sv.siman.com/accesorios/moda?map=categoria,departmento',
'https://sv.siman.com/caballero/moda/ropa?map=sexo,departmento,categoria',
'https://sv.siman.com/caballero/camisas/moda/ropa?map=sexo,sub-categoria,departmento,categoria',
'https://sv.siman.com/caballero/camisetas/moda/ropa?map=sexo,sub-categoria,departmento,categoria',
'https://sv.siman.com/abrigos/caballero/moda/ropa?map=sub-categoria,sexo,departmento,categoria',
'https://sv.siman.com/caballero/moda/ropa/shorts?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/caballero/moda/pantalones/ropa?map=sexo,departmento,sub-categoria,categoria',
'https://sv.siman.com/caballero/jeans/moda/ropa?map=sexo,sub-categoria,departmento,categoria',
'https://sv.siman.com/caballero/camisas/moda/ropa?fuzzy=0&map=sexo,estilo-moda,departmento,categoria&operator=and&query=/caballero/estilo-deportivo/moda/ropa',
'https://sv.siman.com/caballero/moda/ropa/trajes?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/damas/moda/ropa?map=sexo,departmento,categoria',
'https://sv.siman.com/caballero/moda/ropa/trajes?fuzzy=0&map=sub-categoria,sexo,departmento,categoria&operator=and&query=/blazer/caballero/moda/ropa',
'https://sv.siman.com/caballero/moda/xxl?map=sexo,departmento,talla',
'https://sv.siman.com/caballero/moda/ropa/ropa-interior?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/caballero/moda/ropa/ropa-de-dormir?map=sexo,departmento,categoria,sub-categoria',
'https://sv.siman.com/caballero/moda/ropa/shorts?fuzzy=0&map=sexo,departmento,categoria,sub-categoria&operator=and&query=/caballero/moda/ropa/trajes-de-bano/',
'https://sv.siman.com/caballero/calzado/moda?map=sexo,categoria,departmento',
'https://sv.siman.com/accesorios/caballero/moda?map=categoria,sexo,departmento',
'https://sv.siman.com/blusas/moda/nina/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/jeans/moda/nina/pantalones/ropa?map=sub-categoria,departmento,sexo,sub-categoria,categoria',
'https://sv.siman.com/moda/nina/ropa/shorts?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/moda/nina/ropa/vestidos?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/conjuntos/moda/nina/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/moda/nina/ropa/ropa-de-dormir?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/moda/nina/ropa/ropa-interior?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/faldas/moda/nina/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/moda/nina/ropa/traje-de-bano?map=departmento,sexo,categoria,estilo-de-traje-de-bano',
'https://sv.siman.com/abrigos/moda/nina/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/calzado/moda/nina?map=categoria,departmento,sexo',
'https://sv.siman.com/moda/nino?map=departmento,sexo',
'https://sv.siman.com/camisas/moda/nino/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/conjuntos/moda/nino/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/jeans/moda/nino/pantalones/ropa?map=sub-categoria,departmento,sexo,sub-categoria,categoria',
'https://sv.siman.com/moda/nino/ropa/shorts?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/moda/nino/ropa/ropa-interior?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/moda/nino/ropa/ropa-de-dormir?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/moda/nino/ropa/trajes-de-bano?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/abrigos/moda/nino/ropa?map=sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/accesorios/moda/nino?map=categoria,departmento,sexo',
'https://sv.siman.com/calzado/moda/nino?map=categoria,departmento,sexo',
'https://sv.siman.com/bebes/moda/nino?fuzzy=0&map=sexo,departmento&operator=and&query=/bebe-nino/moda',
'https://sv.siman.com/moda/ropa?fuzzy=0&map=sexo,sub-categoria,departmento,categoria&operator=and&page=2&query=/bebe-nino/mamelucos/moda/ropa',
'https://sv.siman.com/bebes/jeans/moda/nino/pantalones/ropa?map=sexo,sub-categoria,departmento,sexo,sub-categoria,categoria',
'https://sv.siman.com/moda/nino/ropa/shorts?map=departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/abrigos/bebes/camisas/moda/nino/ropa?map=sub-categoria,sexo,sub-categoria,departmento,sexo,categoria',
'https://sv.siman.com/bebes/moda/nino/ropa/ropa-interior?map=sexo,departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/bebes/moda/nino/ropa/ropa-de-dormir?map=sexo,departmento,sexo,categoria,sub-categoria',
'https://sv.siman.com/accesorios/bebes/moda/nino?map=categoria,sexo,departmento,sexo',
'https://sv.siman.com/bebes/conjuntos/moda/nino?map=sexo,sub-categoria,departmento,sexo',
'https://sv.siman.com/overall?map=ft',
'https://sv.siman.com/estuche%20para%20beb%C3%A9?map=ft',
'https://sv.siman.com/bebes/moda/nino/trajes-de-bano?map=sexo,departmento,sexo,sub-categoria',
'https://sv.siman.com/calzado/moda/nino?fuzzy=0&map=sexo,categoria,departmento&operator=and&query=/bebe-nino/calzado/moda',
'https://sv.siman.com/bebes/moda/nina?fuzzy=0&map=sexo,departmento&operator=and&query=/bebe-nina/moda',
'https://sv.siman.com/mamelucos?fuzzy=0&map=sexo,ft&operator=and&query=/bebe-nina/mamelucos',
'https://sv.siman.com/bebes/moda/nina/vestidos?map=sexo,departmento,sexo,sub-categoria',
'https://sv.siman.com/faldas/moda/nina?map=sub-categoria,departmento,sexo',
'https://sv.siman.com/abrigos/bebes/camisas/moda/nina?map=sub-categoria,sexo,sub-categoria,departmento,sexo',
'https://sv.siman.com/bebes/moda/nina/ropa-de-dormir?map=sexo,departmento,sexo,sub-categoria',
'https://sv.siman.com/bebes/moda/nina/pantalones/shorts?map=sexo,departmento,sexo,sub-categoria,sub-categoria',
'https://sv.siman.com/bebes/moda/nina/ropa-interior?map=sexo,departmento,sexo,sub-categoria',
'https://sv.siman.com/bebes/moda/nina/trajes-de-bano?map=sexo,departmento,sexo,sub-categoria',
'https://sv.siman.com/accesorios/bebes/moda/nina?map=categoria,sexo,departmento,sexo',
'https://sv.siman.com/bebes/conjuntos/moda/nina?map=sexo,sub-categoria,departmento,sexo',
'https://sv.siman.com/estuche%20para%20beb%C3%A9?map=ft',
'https://sv.siman.com/calzado/moda/nino?fuzzy=0&map=sexo,categoria,departmento&operator=and&query=/bebe-nina/calzado/moda']