# -*- coding: utf-8 -*-
"""
Created on Mon Jun 15 18:03:13 00

@author: ISAAC
"""

# OBTIENE LOS LINKS DE LOS PRODUCTOS
# =============================================================================
# var links = document.querySelectorAll('.vtex-menu-2-x-styledLink--title-menu-sub-cat');
# for(i = 0; i<links.length; i++){
#     console.log("'"+links[i].href+"',");
# }
# =============================================================================

links_sv = [
    'https://sv.siman.com/moda/ropa/blusas',
    'https://sv.siman.com/moda/ropa/camisetas',
    'https://sv.siman.com/moda/ropa/camisas',
    'https://sv.siman.com/moda/ropa/pantalones',
    'https://sv.siman.com/moda/ropa/jeans',
    'https://sv.siman.com/moda/ropa/shorts',
    'https://sv.siman.com/moda/ropa/abrigos',
    'https://sv.siman.com/moda/ropa/vestidos',
    'https://sv.siman.com/moda/ropa/faldas',
    'https://sv.siman.com/moda/ropa/trajes',
    'https://sv.siman.com/moda/ropa/blazer',
    'https://sv.siman.com/moda/ropa/maternidad',
    'https://sv.siman.com/moda/ropa/conjuntos',
    'https://sv.siman.com/moda/ropa/mamelucos',
    'https://sv.siman.com/moda/ropa/estuches',
    'https://sv.siman.com/moda/ropa/ropa-de-dormir',
    'https://sv.siman.com/moda/ropa/ropa-interior',
    'https://sv.siman.com/moda/ropa/trajes-de-bano',
    'https://sv.siman.com/moda/calzado',
    'https://sv.siman.com/moda/accesorios',
    'https://sv.siman.com/muebles-y-hogar/salas',
    'https://sv.siman.com/muebles-y-hogar/muebles-de-television',
    'https://sv.siman.com/muebles-y-hogar/comedores/',
    'https://sv.siman.com/muebles-y-hogar/camas/',
    'https://sv.siman.com/muebles-y-hogar/colchones',
    'https://sv.siman.com/muebles-y-hogar/muebles-de-dormitorio',
    'https://sv.siman.com/muebles-y-hogar/mueble-de-exterior',
    'https://sv.siman.com/muebles-y-hogar/muebles-para-cocina',
    'https://sv.siman.com/muebles-y-hogar/muebles-ocasionales',
    'https://sv.siman.com/muebles-y-hogar/bano',
    'https://sv.siman.com/muebles-y-hogar/dormitorio',
    'https://sv.siman.com/muebles-y-hogar/decoracion',
    'https://sv.siman.com/muebles-y-hogar/cocina/',
    'https://sv.siman.com/muebles-y-hogar/electrodomesticos',
    'https://sv.siman.com/linea-blanca/refrigeradoras',
    'https://sv.siman.com/linea-blanca/cocinas-y-barbacoas',
    'https://sv.siman.com/linea-blanca/lavadoras',
    'https://sv.siman.com/linea-blanca/secadoras',
    'https://sv.siman.com/linea-blanca/aires-acondicionados',
    'https://sv.siman.com/linea-blanca/lavadora-de-platos',
    'https://sv.siman.com/linea-blanca/extractores-de-humo',
    'https://sv.siman.com/linea-blanca/centros-de-lavado',
    'https://sv.siman.com/linea-blanca/oasis-para-agua',
    'https://sv.siman.com/tecnologia/telefonos',
    'https://sv.siman.com/tecnologia/computadoras',
    'https://sv.siman.com/tecnologia/pantallas',
    'https://sv.siman.com/tecnologia/audio-y-video',
    'https://sv.siman.com/tecnologia/smartwatch',
    'https://sv.siman.com/tecnologia/camaras',
    'https://sv.siman.com/articulos-para-bebe/muebles-para-bebe',
    'https://sv.siman.com/articulos-para-bebe/paseo-y-viaje',
    'https://sv.siman.com/articulos-para-bebe/alimentacion-y-cuidado',
    'https://sv.siman.com/articulos-para-bebe/bano-y-aseo',
    'https://sv.siman.com/belleza-e-higiene/maquillaje-para-rostro',
    'https://sv.siman.com/belleza-e-higiene/maquillaje-para-ojos',
    'https://sv.siman.com/belleza-e-higiene/labiales',
    'https://sv.siman.com/belleza-e-higiene/unas',
    'https://sv.siman.com/belleza-e-higiene/cuidado-de-piel',
    'https://sv.siman.com/belleza-e-higiene/accesorios',
    'https://sv.siman.com/belleza-e-higiene/cuidado-del-cabello',
    'https://sv.siman.com/belleza-e-higiene/bano-y-ducha',
    'https://sv.siman.com/belleza-e-higiene/electrobelleza',
    'https://sv.siman.com/belleza-e-higiene/dermocosmetica',
    'https://sv.siman.com/belleza-e-higiene/fragancias',
    'https://sv.siman.com/deportes/gimnasio',
    'https://sv.siman.com/deportes/accesorios-deportivos',
    'https://sv.siman.com/deportes/implementos-de-natacion',
    'https://sv.siman.com/deportes/resistencia',
    'https://sv.siman.com/estilo-de-vida/instrumentos-musicales',
    'https://sv.siman.com/estilo-de-vida/aire-libre',
    'https://sv.siman.com/estilo-de-vida/viaje',
    'https://sv.siman.com/optica/prescripcion',
    'https://sv.siman.com/optica/aros',
    'https://sv.siman.com/optica/lentes-de-contacto',
    'https://sv.siman.com/optica/lentes-clip-on',
    'https://sv.siman.com/optica/soluciones',
    'https://sv.siman.com/optica/accesorios',
    'https://sv.siman.com/libreria/loncheras',
    'https://sv.siman.com/libreria/papeleria',
    'https://sv.siman.com/libreria/articulos-escolares',
    'https://sv.siman.com/libreria/articulos-de-oficina',
    'https://sv.siman.com/juguetes/infantes-y-preescolar',
    'https://sv.siman.com/juguetes/nino',
    'https://sv.siman.com/juguetes/nina',
    'https://sv.siman.com/juguetes/juegos-de-mesa',
    'https://sv.siman.com/juguetes/juegos-de-exterior',
    'https://sv.siman.com/juguetes/montables',
    'https://sv.siman.com/automovil/equipo-de-sonido',
    'https://sv.siman.com/automovil/lavado-y-aroma',
    'https://sv.siman.com/automovil/motor',
    'https://sv.siman.com/automovil/accesorios',
    'https://sv.siman.com/market-corner/alimentos',
    'https://sv.siman.com/market-corner/aseo-y-limpieza',
    'https://sv.siman.com/market-corner/bebidas',
    'https://sv.siman.com/market-corner/cuidado-personal']
